Callculate sum
Ketch92/Multithreading pull request #2
Opened 2021-02-23 17:11 UTC by Ketch92

2021-02-23 19:43 UTC, Fedich09 approved these changes

2021-02-23 19:43 UTC, Fedich09 commented on src/main/java/sum/CustomCallable.java
> +        return list.stream().reduce(0, Integer::sum);
```suggestion
        return list.stream().reduce(Integer::sum);
```

2021-02-23 19:43 UTC, Fedich09 commented on src/main/java/sum/CustomRecursiveTask.java
> +        return list.stream().reduce(0, Integer::sum);
```suggestion
        return list.stream().reduce(Integer::sum);
```

2021-02-23 19:43 UTC, Fedich09 commented on src/main/java/sum/SumWihForJoin.java
> +                .map(ForkJoinTask::join).reduce(0, Integer::sum);
```suggestion
                .map(ForkJoinTask::join).reduce(Integer::sum);
```

2021-02-23 19:43 UTC, Fedich09 commented on src/main/java/sum/SumWihForJoin.java
> +public class SumWihForJoin {
```suggestion
public class SumWithForJoin {
```

2021-02-23 19:43 UTC, Fedich09 commented on src/main/java/sum/Summing.java
> +        return list.stream().reduce(0, Integer::sum);
```suggestion
        return list.stream().reduce(Integer::sum);
```

2021-02-23 19:57 UTC, Ketch92 commented on src/main/java/sum/SumWihForJoin.java
> +public class SumWihForJoin {
refactored

2021-02-24 11:59 UTC, Sofasmile requested changes

2021-02-24 11:59 UTC, Sofasmile commented on src/main/java/sum/Summing.java
> +public class Summing {
не зовсім зрозуміло для чого потрібен цей клас. В нього явно не одна зона відповідальності
Пропоную його трохи переробити. Зробити так щоб в класі був один метод, який буде створювати рандомний список чисел і повертати його. На вхід може приймати допоміжні параметри
А метод getSum() і sum() використовуються лише для тестування, тому їх треба перенести безпоседеньо в тести

2021-02-24 11:59 UTC, Sofasmile commented on src/test/java/sum/SumWihForJoinTest.java
> +    public void testRandomlyGeneratedList() {
загалом один тест кейс не покриває всі можливі варіанти роботи програми. Май на увазі в майбутньому. Проте для даного завдання можеш залишити як є

2021-02-24 12:50 UTC, Ketch92 commented on src/main/java/sum/Summing.java
> +public class Summing {
Згоден, в цьому завданні я не дуже слідував SRP

2021-02-24 12:51 UTC, Ketch92 commented on src/test/java/sum/SumWihForJoinTest.java
> +    public void testRandomlyGeneratedList() {
Звісно, я це розумів. Просто тест провіряє суму. І якби принцип додавання всьюди один. Тому дуже заморочуватися не було сенсу.

2021-02-24 14:52 UTC, Sofasmile approved these changes

2021-02-24 14:54 UTC, merged